# Backend Port
server.port=8082

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/attendancedb
spring.datasource.username=vivekiyer
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
# 'update' automatically creates the tables based on your Java Entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true