# Change Port
server.port=8082

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:attendance_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enable H2 Console in Browser (THIS FIXES THE 404)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always